### ISSUE TITLE
Allow the selection of a "random element" of another sobject

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/Snowfakery#125]
Two variants?

1. A random one created in this batch.
2. A random one created ever.

**Comment by acrosman** [comment]
Looks like this is being addressed in #184.

Thinking about how this would be useful, being able to limit that random selection to a reliable sub-set of generated records would be helpful.  In the Salesforce context that could RecordType, in other contexts similar concepts apply -- subtypes are hardly a rare use case.

Since adding a whole capacity to filter within that drafted `random_reference` function could get massively complex it seems like maybe a solution that tied nicknames to a set of records when the count on an object is greater than one might work.  Currently each nickname references just one record, and when used on an object getting several records created it ends up linked to the last record in that set.  If instead nickname could stay attached to the whole set (and have either a grandfathered behavior of using last generated when referenced directly, or an implied `random_reference` when used directly), that collection could be used to select arbitrary connections.

**Comment by prescod** [comment]
@acrosman Yes I agree this would be a useful feature. The issue is that Snowfakery's "memory" size is constant no matter how big your dataset. Deep trees do use more memory than shallow ones, but they use the same amount whether you generate a million rows or 100 million.

I have roughly two ideas for implementing what you describe.

1. Use a disk-based cache to manage the "sets" you are talking about. This will somewhat (slightly?) slow Snowfakery down and make it require O(N) disk space. (CCI itself does already use O(N) space for ID->OID mapping but Snowfakery doesn't)
2. I could encode nicknames into object's IDs instead of having them be flat integers

I didn't think of the second solution until recently and haven't tried it out yet.

The second solution is backwards-incompatible with any code that used the "random number hack" to implement this random reference feature. Which I guess is one reason that it might make sense to ship a simple version of the feature which replaces the random number hack, and then update all scripts to use the feature and then change the ID format in a few months.

**Comment by acrosman** [comment]
@prescod is there an mixed solution like #2 where Snowfakery adds a private field like `__nickname_set` that gets the nickname field when generating? It seems like that could allow you to search for those records the same way you would if they were part of the ID without disrupting your existing solution (which seems useful in other contexts, although it seems like setting the nickname _and_ wanting that solution would be a rare use case).

**Comment by acrosman** [comment]
Never mind, I realized where your memory challenge is coming from, Snowfakery isn't storing those values it generates and dumps. So to look back to a previously generated value it has to know how to guess or calculate the right matches.  My solution does not help you there at all.

**Comment by acrosman** [comment]
I keep coming back to this problem in my head. Since snowfakery only needs to be able to calculate matches it seems like it could keep a small index of nicknamed ID ranges (created instead of a direct reference when count is actively set to by greater than one. Something like: 
`[Nickname] -> ([object_type], [StartId], [EndId])`

If you wanted to included everything that used the nickname (if it were running in a larger loop for some reason), the IDs could be a series of ranges:
`[Nickname] -> ([object_type], ([StartId1], [EndId1]), ([StartId2], [EndId2]), ..., ([StartIdN], [EndIdN]))`

In theory I think it might be possible to write a recipe that used lots of tiny iterations would cause that pattern to have memory consumption technically measure at O(N) but likely you'd have to work pretty hard to make that consume enough memory to cause trouble in practice. 

The first design is also arguably a good parallel to the general behavior of nicknames to just be the most recent reference. With the index you could then select IDs in the range with the proposed function AND create yourself a backward compatible behavior of simply using the last reference from the index when the nickname is encountered as a reference field.

**Comment by prescod** [comment]
We can open new issues for the cases that are not covered.
